name: Plugin Submission
description: Submit a new plugin to the archive
assignees: Hecter94
labels: New Submission
title: New Plugin Submission
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in submitting a plugin to the archive.
        Please check our [Plugin List](https://github.com/Hecter94/EndlessSky-PluginArchive/tree/issue-template/res/pluginlist) before submission to ensure it has not already been added before creating a new issue.

        If the plugin is already in the archive and you want to rename or update it, please open a Pull Request.
        If you have any questions regarding this form, please check our [README](https://github.com/Hecter94/EndlessSky-PluginArchive/blob/main/README.md#add-your-plugin)

  - type: input
    attributes:
      label: Name
      description: Enter the name of the plugin.
    validations:
      required: true
  - type: input
    attributes:
      label: Author
      description: Enter the plugin author; if yourself, enter how you want to be listed.
    validations:
      required: true
  - type: input
    attributes:
      label: Website
      description: Please provide a valid website URL if the plugin is hosted online.
    validations:
      required: false
  - type: input
    attributes:
      label: Direct Link
      description: |
        (Highly Recommended) Entering a direct link to the plugin's .zip file will enable automatic updating, allowing the archive to stay up-to-date with any changes.
        If you do not provide a direct link, you must upload and attach the plugin to this issue. Be aware that GitHub has a 25MB maximum upload size.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Category
      description: Please select a category for the plugin to be listed as.
      options:
        - Cheats
        - Gameplay
        - Graphics
        - Outfits
        - Overhauls
        - Patches
        - Races
        - Ships
        - Starts
        - Story
        - Weapons
        - Uncategorized
    validations:
      required: true
  - type: input
    attributes:
      label: Status
      description: Please enter the current status of the plugin, whether it is complete, in progress, abandoned, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Description
      description: Please include a short description of the plugin.
    validations:
      required: true
