import json


def main():
    print('LEESt Scripts -> Escort Builder')
    filepath = input('File path to ships list > ')
    variant_weight = input('Variant weight (variant <n>) > ')
    ship_number = input('Number of ships > ')
    escortbuilder(filepath, variant_weight, ship_number)

def escortbuilder(filepath, variant_weight, ship_number):
    print('#### BEGIN SCRIPT-GENERATED CODE ####')

    ls = json.loads(open(filepath).read())
    itms = []

    for i in ls:
        for a in i:
            for lsa in ls:
                for lsb in lsa:
                    itms.append([a, lsb])

    for itm in itms:
        # Prevent duplicates
        if len(set(itm)) == 1:
            continue

        print(f'variant {variant_weight}')
        for ship in itm:
            print(f'\t"{ship}" {ship_number}')


    print('#### END SCRIPT-GENERATED CODE ####')
    print('# This code was generated by a script')
    print('# as it is not feasible for this to be')
    print('# written manually')


if __name__ == '__main__':
    main()