name: Automatic make readme
on: 
  schedule: 
    - cron: '30 4 * * *' 
    # runs at 04:30 am utc every day
    # minute(0-59) / hour(0-23) / day of month(1-31) / month(1-12) / day of week(0-6)
jobs:
  First:
    name: First job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install beautifulsoup4 and Pillow
        run: |
          python3 -m pip install bs4
          python3 -m pip install lxml
          python3 -m pip install Pillow
      - name: Make README.md
        run: python res/src/makemd.py
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add .
          git commit -m "Plugin md generated" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
